### ISSUE TITLE
StreamSpotOrderbook blocked when there is no update on the market

### ISSUE THREAD

**Issue by powenperng** [InjectiveLabs/sdk-go#75] opened 2022-10-24 02:34 UTC
`
stream, err := exchangeClient.StreamSpotOrderbook(ctx, marketIds)
`
As the example on api doc, if there is no update on the market during you call the function. It will be blocked, can't have the stream object until there is an update happend on the market.

**Comment by achilleas-kal** [comment] 2022-10-27 23:11
@powenperng so the call works but you get a response only when there is an update in the market?

Isn't that expected? Stream will return you responses when there's an update.

**Comment by powenperng** [comment] 2022-10-28 01:13
Yes, the issue is if no update happend. the thread will be block on this line, until there is an update.

**Comment by achilleas-kal** [comment] 2022-10-28 07:34
@powenperng the stream works that way so it's normal, if there is no update for 1h the exchange will cut the connection and then a re-try on the client-side will establish the connection again.

**Comment by maximshen007** [comment] 2023-02-08 15:22
This is a very odd or blizzard design. Client should at least get a message from that stream to be notified that stream will be closed, if client doesn't response to keep it alive, it will be closed in X mins

**Comment by achilleas-kal** [comment] 2023-02-08 16:15
This is already what happens, you catch the exception on the connection closure, re-try and establish it once again.

All clients should have re-try logic, networking issues that cannot be foreseen either on the client or the server can also cut the connection momentarily.

How exactly should the friendlier design be?

**Comment by maximshen007** [comment] 2023-02-08 16:24
This is called un-gracefully disconnection. The graceful way should prevent that stream from shutting down w/o asking the client if it could be closed. Having client apps keep retrying is sth unheard of from a normal API user standpoint.

**Comment by achilleas-kal** [comment] 2023-02-08 16:25
The way to do that would be to introduce a keep alive mechanism which was decided not to do for performance issues.

**Comment by maximshen007** [comment] 2023-02-08 16:32
If we just ask users to confirm if they still need to keep it alive for every 24 hours, I don't think it will hurt performance.

**Comment by vinhphuctadang** [comment] 2023-04-12 02:13
We will deprecate this API in next days so the issue is not valid anymore

**Closed by vinhphuctadang** 2023-04-12 02:13 UTC
